name: Deploy to GitHub Pages
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install GH pages
        run: npm install gh-pages --legacy-peer-deps --save-dev

      - name: Build the app
        run: npm run build
  
# Deployment job
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build

        - name: Deploy server
          run: npm run gh-pages -d .
